//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 15/05/2015 12:58:41
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace OptimusContext
{

    /// <summary>
    /// There are no comments for OptimusContext.RhMark in the schema.
    /// </summary>
    [Table(Name = @"shirka_v2.rh_mark")]
    public partial class RhMark : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Card;

        private System.DateTime _Date;
        #pragma warning restore 0649

        private EntitySet<RhIncidence> _RhIncidences;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnCardChanging(string value);
        partial void OnCardChanged();
        partial void OnDateChanging(System.DateTime value);
        partial void OnDateChanged();
        #endregion

        public RhMark()
        {
            this._RhIncidences = new EntitySet<RhIncidence>(new Action<RhIncidence>(this.attach_RhIncidences), new Action<RhIncidence>(this.detach_RhIncidences));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Card in the schema.
        /// </summary>
        [Column(Name = @"card", Storage = "_Card", DbType = "VARCHAR(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Card
        {
            get
            {
                return this._Card;
            }
            set
            {
                if (this._Card != value)
                {
                    this.OnCardChanging(value);
                    this.SendPropertyChanging();
                    this._Card = value;
                    this.SendPropertyChanged("Card");
                    this.OnCardChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Date in the schema.
        /// </summary>
        [Column(Name = @"`date`", Storage = "_Date", CanBeNull = false, DbType = "DATETIME NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                if (this._Date != value)
                {
                    this.OnDateChanging(value);
                    this.SendPropertyChanging();
                    this._Date = value;
                    this.SendPropertyChanged("Date");
                    this.OnDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for RhIncidences in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="RhMark_RhIncidence", Storage="_RhIncidences", ThisKey="Id", OtherKey="MarkId", DeleteRule="RESTRICT")]
        public EntitySet<RhIncidence> RhIncidences
        {
            get
            {
                return this._RhIncidences;
            }
            set
            {
                this._RhIncidences.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_RhIncidences(RhIncidence entity)
        {
            this.SendPropertyChanging("RhIncidences");
            entity.RhMark = this;
        }
    
        private void detach_RhIncidences(RhIncidence entity)
        {
            this.SendPropertyChanging("RhIncidences");
            entity.RhMark = null;
        }
    }

}
