//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 5/18/2015 6:50:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace OptimusContext
{

    [DatabaseAttribute(Name = "shirka_v2")]
    [ProviderAttribute(typeof(Devart.Data.MySql.Linq.Provider.MySqlDataProvider))]
    public partial class OptimusDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(OptimusDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertLibraryLibrarian(LibraryLibrarian instance);
        partial void UpdateLibraryLibrarian(LibraryLibrarian instance);
        partial void DeleteLibraryLibrarian(LibraryLibrarian instance);
        partial void InsertRhIncidence(RhIncidence instance);
        partial void UpdateRhIncidence(RhIncidence instance);
        partial void DeleteRhIncidence(RhIncidence instance);
        partial void InsertRhMark(RhMark instance);
        partial void UpdateRhMark(RhMark instance);
        partial void DeleteRhMark(RhMark instance);
        partial void InsertRhSchedule(RhSchedule instance);
        partial void UpdateRhSchedule(RhSchedule instance);
        partial void DeleteRhSchedule(RhSchedule instance);
        partial void InsertLibraryOffice(LibraryOffice instance);
        partial void UpdateLibraryOffice(LibraryOffice instance);
        partial void DeleteLibraryOffice(LibraryOffice instance);

        #endregion

        public OptimusDataContext() :
        base(GetConnectionString("OptimuDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public OptimusDataContext(MappingSource mappingSource) :
        base(GetConnectionString("OptimuDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public OptimusDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public OptimusDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public OptimusDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public OptimusDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<LibraryLibrarian> LibraryLibrarians
        {
            get
            {
                return this.GetTable<LibraryLibrarian>();
            }
        }

        public Devart.Data.Linq.Table<RhIncidence> RhIncidences
        {
            get
            {
                return this.GetTable<RhIncidence>();
            }
        }

        public Devart.Data.Linq.Table<RhMark> RhMarks
        {
            get
            {
                return this.GetTable<RhMark>();
            }
        }

        public Devart.Data.Linq.Table<RhSchedule> RhSchedules
        {
            get
            {
                return this.GetTable<RhSchedule>();
            }
        }

        public Devart.Data.Linq.Table<LibraryOffice> LibraryOffices
        {
            get
            {
                return this.GetTable<LibraryOffice>();
            }
        }
    }
}
